[browser]
gatherUsageStats = false

[server]
enableCORS = true
enableXsrfProtection = true
headless = true
port = 8501
baseUrlPath = ""
sslCertFile = ".streamlit/localhost.crt"
sslKeyFile = ".streamlit/localhost.key"
